INSERT INTO TB_USUARIOS (EMAIL, NOME, SENHA) VALUES ('joao@gmail.com', 'João da Silva', '42442a6c2b4ef409144e8573115b621f');
INSERT INTO TB_USUARIOS (EMAIL, NOME, SENHA) VALUES ('jose@gmail.com', 'José da Silva', '42aafd8e16bbc88aa6d978a7841d8618');
INSERT INTO TB_USUARIOS (EMAIL, NOME, SENHA) VALUES ('maria@gmail.com', 'Maria Pereira', '1bf0eab4cc70d79d2ad312968275553c');
INSERT INTO TB_USUARIOS (EMAIL, NOME, SENHA) VALUES ('josefa@gmail.com', 'Josefa Maia', 'dd6f8500f1808740e7fab01392a1d129');
INSERT INTO TB_USUARIOS (EMAIL, NOME, SENHA) VALUES ('pedro@gmail.com', 'Pedro Cavalcante', 'c289f59a36799210142e5d74574a03a3');

INSERT INTO TB_TAREFAS (ATUALIZADO_EM, CONCLUIDO, CRIADO_EM, DATA_FINAL, DESCRICAO, PRIORIDADE, TITULO, FK_USUARIO) VALUES(NULL, FALSE, '2022-02-23', '2022-03-23', 'Limpar a casa', 'ALTA', 'Limpar a casa', 1);
INSERT INTO TB_TAREFAS (ATUALIZADO_EM, CONCLUIDO, CRIADO_EM, DATA_FINAL, DESCRICAO, PRIORIDADE, TITULO, FK_USUARIO) VALUES(NULL, FALSE, '2022-02-23', '2022-03-23', 'Limpar a casa', 'ALTA', 'Limpar a casa', 2);
INSERT INTO TB_TAREFAS (ATUALIZADO_EM, CONCLUIDO, CRIADO_EM, DATA_FINAL, DESCRICAO, PRIORIDADE, TITULO, FK_USUARIO) VALUES(NULL, FALSE, '2022-02-23', '2022-03-23', 'Limpar a casa', 'ALTA', 'Limpar a casa', 3);
INSERT INTO TB_TAREFAS (ATUALIZADO_EM, CONCLUIDO, CRIADO_EM, DATA_FINAL, DESCRICAO, PRIORIDADE, TITULO, FK_USUARIO) VALUES(NULL, FALSE, '2022-02-23', '2022-03-23', 'Limpar a casa', 'ALTA', 'Limpar a casa', 4);
INSERT INTO TB_TAREFAS (ATUALIZADO_EM, CONCLUIDO, CRIADO_EM, DATA_FINAL, DESCRICAO, PRIORIDADE, TITULO, FK_USUARIO) VALUES(NULL, FALSE, '2022-02-23', '2022-03-23', 'Limpar a casa', 'ALTA', 'Limpar a casa', 5);
INSERT INTO TB_TAREFAS (ATUALIZADO_EM, CONCLUIDO, CRIADO_EM, DATA_FINAL, DESCRICAO, PRIORIDADE, TITULO, FK_USUARIO) VALUES(NULL, FALSE, '2022-02-23', '2022-03-23', 'Limpar a casa', 'ALTA', 'Limpar a casa', 1);
INSERT INTO TB_TAREFAS (ATUALIZADO_EM, CONCLUIDO, CRIADO_EM, DATA_FINAL, DESCRICAO, PRIORIDADE, TITULO, FK_USUARIO) VALUES(NULL, FALSE, '2022-02-23', '2022-03-23', 'Limpar a casa', 'ALTA', 'Limpar a casa', 2);
INSERT INTO TB_TAREFAS (ATUALIZADO_EM, CONCLUIDO, CRIADO_EM, DATA_FINAL, DESCRICAO, PRIORIDADE, TITULO, FK_USUARIO) VALUES(NULL, FALSE, '2022-02-23', '2022-03-23', 'Arrumar o quarto da sua irmã', 'BAIXA', 'Arrumar o quarto da irmã', 3);

INSERT INTO TB_TAREFAS (ATUALIZADO_EM, CONCLUIDO, CRIADO_EM, DATA_FINAL, DESCRICAO, PRIORIDADE, TITULO, FK_USUARIO) VALUES(NULL, FALSE, '2022-02-23', '2022-03-23', 'Lavar o box, a privada e a pia', 'BAIXA', 'Lavar o banheiro', 2);
INSERT INTO TB_TAREFAS (ATUALIZADO_EM, CONCLUIDO, CRIADO_EM, DATA_FINAL, DESCRICAO, PRIORIDADE, TITULO, FK_USUARIO) VALUES(NULL, FALSE, '2022-02-23', '2022-03-23', 'Limpar caixa de areia do gato, recolher a sujeira num saco e jogar fora.', 'ALTA', 'Limpar caixa do gato', 5);
INSERT INTO TB_TAREFAS (ATUALIZADO_EM, CONCLUIDO, CRIADO_EM, DATA_FINAL, DESCRICAO, PRIORIDADE, TITULO, FK_USUARIO) VALUES(NULL, FALSE, '2022-02-23', '2022-03-23', 'Recolher as roupas no varal, separando-as pelos respectivos donos.', 'MEDIA', 'Recolher roupas', 4);
INSERT INTO TB_TAREFAS (ATUALIZADO_EM, CONCLUIDO, CRIADO_EM, DATA_FINAL, DESCRICAO, PRIORIDADE, TITULO, FK_USUARIO) VALUES(NULL, FALSE, '2022-02-23', '2022-03-23', 'Lixar, pintar e passar verniz na porta de entrada', 'BAIXA', 'Pintar porta da frente', 3);